name: Setup
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        bun install --frozen-lockfile
