name: Setup
runs:
  using: "composite"
  steps:
    - name: Install Node.js 18.x
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 22.x
        cache: npm
        registry-url: "https://registry.npmjs.org"

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        pnpm install
