name: Setup
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
      with:
        bun-version: latest

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        bun install --frozen-lockfile
