name: Setup
runs:
  using: 'composite'
  steps:
    - name: Install Node.js 18.x
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
      with:
        node-version: 18.x
        cache: npm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        pnpm install
