packages:
  - packages/*
  - services/api/
  - services/clarity/
  - services/sleepymaid/
  - services/helper/
  - services/watcher/
  - services/website/
  - services/testbot/

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
