packages:
  - packages/*
  - services/api/
  - services/clarity/
  - services/sleepymaid/
  - services/helper/
  - services/watcher/
  - services/website/
  - services/testbot/
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - unrs-resolver
